### ISSUE TITLE
In windows 10 64 bit os : problem with OpenPose

### ISSUE THREAD

**Issue by AditSoni** [chonyy/AI-basketball-analysis#7] opened 2020-05-31 16:32 UTC
Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "C:\WORKSP~1\python\CONDA\BASKET~1\AI-BAS~1\venv\lib\site-packages\werkzeug\wsgi.py", line 506, in __next__
    return self._next()
  File "C:\WORKSP~1\python\CONDA\BASKET~1\AI-BAS~1\venv\lib\site-packages\werkzeug\wrappers\base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "C:\Workspace\python\CONDA\Basketball_shooting_pose\AI-basketball-analysis\src\app_helper.py", line 19, in getVideoStream     
    datum, opWrapper = openpose_init()
  File "C:\Workspace\python\CONDA\Basketball_shooting_pose\AI-basketball-analysis\src\utils.py", line 47, in openpose_init
    raise e
  File "C:\Workspace\python\CONDA\Basketball_shooting_pose\AI-basketball-analysis\src\utils.py", line 39, in openpose_init
    import OpenPose.Release.pyopenpose as op
ModuleNotFoundError: No module named 'OpenPose.Release.pyopenpose'

**Comment by chonyy** [comment] 2020-05-31 19:41
Hi, I found out that there are some files lost in the repo.
I have added them back into it.
Please clone the new repo and check if the problem is fixed now.
Thanks a lot for finding the bug.

**Comment by AditSoni** [comment] 2020-06-01 00:45
thanks dude

Sent from Yahoo Mail on Android 
 
  On Mon, Jun 1, 2020 at 1:12 AM, Tony Chou<notifications@github.com> wrote:   


Hi, I found out that there are some files lost in the repo.
I have added them back into it.
Please clone the new repo and check if the problem is fixed now.
Thanks a lot for finding the bug.

**Comment by chonyy** [comment] 2020-06-01 11:01
NP man. Check out the upload directory, there are some sample videos for you to play with.

**Closed** 2020-06-01 11:01 UTC
